# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Frontend to Azure Web App - WebProjectFrontEnd

on:
  push:
    branches:
      - main
    paths:
      - 'frontend_TS/**'
      - '.github/workflows/main_webprojectfrontend.yml'
  workflow_dispatch:  # Keep this to allow manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Build frontend
        run: |
          cd frontend_TS
          npm ci
          # Set the API URL to point to your backend
          echo "VITE_API_BASE_URL=https://webprojectbackend.azurewebsites.net" > .env
          npm run build

      - name: Zip artifact for deployment
        run: |
          cd frontend_TS/dist
          zip -r ../../frontend-release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: frontend-release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip frontend-release.zip

      # For SPA routing with React/Vue, create a web.config file
      - name: Create web.config for SPA routing
        run: |
          cat > web.config << 'EOL'
          <?xml version="1.0" encoding="utf-8"?>
          <configuration>
            <system.webServer>
              <rewrite>
                <rules>
                  <rule name="SPA Routes" stopProcessing="true">
                    <match url=".*" />
                    <conditions logicalGrouping="MatchAll">
                      <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                    </conditions>
                    <action type="Rewrite" url="/" />
                  </rule>
                </rules>
              </rewrite>
              <staticContent>
                <mimeMap fileExtension=".webmanifest" mimeType="application/manifest+json" />
              </staticContent>
            </system.webServer>
          </configuration>
          EOL
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FRONTEND }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_FRONTEND }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_FRONTEND }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'WebProjectFrontEnd'
          slot-name: 'Production'
          package: .