# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Laravel Backend to Azure Web App - WebProjectBackEnd
 
on:
  push:
    branches:
      - main
    paths:
      - 'backend_Laravel/**'
      - '.github/workflows/main_webprojectbackend.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, dom, fileinfo, sqlite3, pdo_sqlite
          tools: composer:v2

      - name: Set up backend directory
        run: |
          cd backend_Laravel
          composer install --no-dev --optimize-autoloader
          cat > .env << 'EOL'
          APP_NAME=Lume
          APP_ENV=production
          APP_KEY=base64:IGtdSyUcU/95yJuLbsVO0FxpBddKAZSBknBkENVKI+g=
          APP_DEBUG=true
          APP_URL=https://webprojectbackend.azurewebsites.net
          DB_CONNECTION=sqlite
          DB_DATABASE=/home/site/wwwroot/database.db
          LOG_CHANNEL=stack
          BROADCAST_DRIVER=log
          CACHE_DRIVER=file
          FILESYSTEM_DISK=local
          QUEUE_CONNECTION=sync
          SESSION_DRIVER=file
          SESSION_LIFETIME=120
          GITHUB_AI_KEY=${{ secrets.AI_API_KEY }}
          CORS_ALLOWED_ORIGINS=https://webprojectfrontend.azurewebsites.net
          EOL

      - name: Zip artifact for deployment
        run: |
          cd backend_Laravel
          zip -r ../release.zip ./*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: php-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: php-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_7F107CC8CD16456EB6E3382DD7A670E3 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B51D737D0BD0492DA74EE27A2E80F279 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_482E2D2D5B1546C78323F415968B2574 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'WebProjectBackEnd'
          slot-name: 'Production'
          package: .

      - name: 'Setup database and run migrations'
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az webapp ssh --name WebProjectBackEnd --resource-group Web_Project --timeout 180 --port 2222 << EOF
            # Create web.config for IIS/Azure with proper URL rewriting
            cat > /home/site/wwwroot/web.config << 'EOL'
            <?xml version="1.0" encoding="UTF-8"?>
            <configuration>
              <system.webServer>
                <rewrite>
                  <rules>
                    <!-- Handle direct URLs without index.php -->
                    <rule name="Laravel Routes" stopProcessing="true">
                      <match url="^((?!index\.php).+)$" />
                      <conditions logicalGrouping="MatchAll">
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                      </conditions>
                      <action type="Rewrite" url="index.php/{R:1}" appendQueryString="true" />
                    </rule>
                    <!-- Handle index.php/route URLs -->
                    <rule name="Laravel Routes with index.php" stopProcessing="true">
                      <match url="^index\.php/(.*)$" />
                      <action type="Rewrite" url="index.php/{R:1}" appendQueryString="true" />
                    </rule>
                    <!-- Handle all URLs that don't match files or folders -->
                    <rule name="Laravel Fallback" stopProcessing="true">
                      <match url=".*" />
                      <conditions>
                        <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                        <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                      </conditions>
                      <action type="Rewrite" url="index.php" appendQueryString="true" />
                    </rule>
                  </rules>
                </rewrite>
                <httpProtocol>
                  <customHeaders>
                    <add name="Access-Control-Allow-Origin" value="https://webprojectfrontend.azurewebsites.net" />
                    <add name="Access-Control-Allow-Headers" value="Content-Type, Authorization, X-Requested-With" />
                    <add name="Access-Control-Allow-Methods" value="GET, POST, PUT, DELETE, OPTIONS" />
                    <add name="Access-Control-Allow-Credentials" value="true" />
                  </customHeaders>
                </httpProtocol>
              </system.webServer>
            </configuration>
            EOL
            
            # Create .htaccess for Apache with proper CORS headers
            cat > /home/site/wwwroot/public/.htaccess << 'EOL'
            <IfModule mod_rewrite.c>
                <IfModule mod_negotiation.c>
                    Options -MultiViews -Indexes
                </IfModule>
                
                RewriteEngine On
                
                # Handle Authorization Header
                RewriteCond %{HTTP:Authorization} .
                RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
                
                # Redirect Trailing Slashes If Not A Folder...
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteCond %{REQUEST_URI} (.+)/$
                RewriteRule ^ %1 [L,R=301]
                
                # Send Requests To Front Controller...
                RewriteCond %{REQUEST_FILENAME} !-d
                RewriteCond %{REQUEST_FILENAME} !-f
                RewriteRule ^ index.php [L]
            </IfModule>
            
            # Add CORS headers
            <IfModule mod_headers.c>
                Header set Access-Control-Allow-Origin "https://webprojectfrontend.azurewebsites.net"
                Header set Access-Control-Allow-Methods "GET, POST, PUT, DELETE, OPTIONS"
                Header set Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept, Authorization"
                Header set Access-Control-Allow-Credentials "true"
                
                # Handle OPTIONS preflight requests
                RewriteEngine On
                RewriteCond %{REQUEST_METHOD} OPTIONS
                RewriteRule ^(.*)$ $1 [R=200,L]
            </IfModule>
            EOL
            
            # Fix environment file to have proper path to database.db
            cat > /home/site/wwwroot/.env << 'EOL'
            APP_NAME=Lume
            APP_ENV=production
            APP_KEY=base64:IGtdSyUcU/95yJuLbsVO0FxpBddKAZSBknBkENVKI+g=
            APP_DEBUG=true
            APP_URL=https://webprojectbackend.azurewebsites.net
            DB_CONNECTION=sqlite
            DB_DATABASE=/home/site/wwwroot/database.db
            LOG_CHANNEL=stack
            BROADCAST_DRIVER=log
            CACHE_DRIVER=file
            FILESYSTEM_DISK=local
            QUEUE_CONNECTION=sync
            SESSION_DRIVER=file
            SESSION_LIFETIME=120
            GITHUB_AI_KEY=${{ secrets.AI_API_KEY }}
            CORS_ALLOWED_ORIGINS=https://webprojectfrontend.azurewebsites.net
            EOL
            
            # Create database and correct permissions
            touch /home/site/wwwroot/database.db
            chmod 777 /home/site/wwwroot/database.db
            chmod -R 777 /home/site/wwwroot/storage
            chmod -R 777 /home/site/wwwroot/bootstrap/cache
            
            # Clear all Laravel caches first before rebuilding
            cd /home/site/wwwroot
            php artisan config:clear
            php artisan cache:clear
            php artisan route:clear
            php artisan view:clear
            
            # Run migrations and seed database
            php artisan migrate:fresh --force
            php artisan tinker --execute="use App\\Models\\Users; Users::create(['username' => 'admin', 'email' => 'c@c.c', 'password' => bcrypt('P@\$\$w0rd'), 'Role' => 'admin', 'IsApproved' => true]);"
            
            # Rebuild cache after all files are updated
            php artisan config:cache
            php artisan route:cache
            EOF
